spring:
  batch:
    jdbc:
      initialize-schema: always
  profiles:
    active: local
server:
  port: 8080
---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
      generate-ddl: true
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/khumu
      username: root
      password: Janghoon1101!
      driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  profiles: gcp
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
      generate-ddl: true
      show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://34.64.100.109:3306/khumu
      username: root
      password: Janghoon1101!
      driver-class-name: com.mysql.cj.jdbc.Driver
---
#  batch:
#    job:
#      names: ${job.name:NONE}
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  data:
#    rest:
#      base-path: /api
#  h2:
#    console:
#      enabled: true
---
#spring:
#  profiles: local
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
---



