spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 이거 안해주면 구동은 가능하지만, 에러메시지 몇개 뜸. 해주는게 좋음

    hikari:
      username: root
      password: Janghoon1101!

  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8080

--- # Local 환경
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
      generate-ddl: true
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/khumu

--- # Dev 환경, gcp-appengine에 연결되어있다.
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
      generate-ddl: true
      show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://34.64.100.109:3306/khumu

--- # 개인 설정 환경
sns :
  dev : arn:aws:sns:ap-northeast-2:590304977225:khumu-messaging-dev
  local : arn:aws:sns:ap-northeast-2:590304977225:khumu-messaging-local


