spring:
  profiles:
    active: mysql
#  batch:
#    job:
#      names: ${job.name:NONE}
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  data:
#    rest:
#      base-path: /api
#  h2:
#    console:
#      enabled: true
---
#spring:
#  profiles: local
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://34.64.201.199/khumu_announcement_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: Khu123123!@
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080